# User Goal Adherence Testing Configuration

# Path to conversations file created by run_pipeline
conversations_path: "../../results/0624_eval_env_goal_split/conversations.json"

user_goal_adherence_testing:
  # LLM configuration for assessment
  assessment_litellm:
    model: gpt-4.1-mini
    temperature: 0.1
    top_p: 0.9
    timeout: 30
    caching: true
  
  # Test parameters
  test:
    results_output_dir: "../../results/user_goal_adherence_testing"
    
  # Assessment parameters
  assessment:
    concurrency: 20
    scoring_threshold: 0.8  # Minimum score to consider user as adhering to goal
    
  # Message analysis parameters
  message_analysis:
    # Whether to include system messages in analysis (usually false)
    include_system_messages: false
    # Whether to include tool messages in analysis (usually false) 
    include_tool_messages: false
    # Whether to include assistant messages with tool calls in analysis (usually false)
    include_tool_call_messages: false 