# Personality Adherence Testing Configuration

# Path to conversations file
conversations_path: "/Users/kudrinsky/Documents/afma/results/gpt-4-1-mini/big_eval/conversations.json"

# Output directory for results
output_dir: "results/gpt-4-1-mini/big_eval/personality_adherence"

personality_adherence_testing:
  # LLM configuration for assessment
  assessment_litellm:
    model: gpt-4.1-mini
    temperature: 0.1
    max_tokens: 10
    timeout: 30
    caching: true 